# See https://wiki.hyprland.org/Configuring/Monitors/
# monitor=,preferred,auto,auto
monitor=eDP-1,highres,2895x1440,1.5
monitor=desc:LG Electronics LG ULTRAGEAR 305NTXR7Z626,prefered,2560x0,1
monitor=desc:LG Electronics LG ULTRAGEAR 305NTWG7Z625,prefered,0x0,1
