# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

$monitor_1 = desc:LG Electronics LG ULTRAGEAR 305NTXR7Z626
$monitor_2 = desc:LG Electronics LG ULTRAGEAR 305NTWG7Z625

workspace = 1, monitor:$monitor_1
workspace = 2, monitor:$monitor_1
workspace = 3, monitor:$monitor_1
workspace = 4, monitor:$monitor_1
workspace = 5, monitor:$monitor_1

workspace = 6, monitor:$monitor_2
workspace = 7, monitor:$monitor_2
workspace = 8, monitor:$monitor_2
workspace = 9, monitor:$monitor_2
workspace = 10, monitor:$monitor_2

windowrule = suppress_event maximize, match:class .*

# touch of opacity for all
windowrule = opacity 0.97 0.9, match:tag ^(?!.*terminal).*$
windowrule = opacity .90, match:tag terminal

# Fix some draggin issues with XWayland
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1,fullscreen 0, match:pin 0

windowrule = tag +floating-window, match:class (blueberry.py|org.pulseaudio.pavucontrol|org.gnome.Nautilus|com.gabm.satty|TUI.float)
windowrule = tag +floating-window, match:class (xdg-desktop-portal-gtk|org.gnome.Nautilus), match:title ^(Open.*Files?|Open [F|f]older.*|Save.*Files?|Save.*As|Save|All Files|.*wants to [open|save].*|[C|c]hoose.*)
windowrule = tag +floating-window, match:title ^impala$

windowrule = float on, match:class org.gnome.Calculator
# Floating windows
windowrule = float on, match:tag floating-window
windowrule = center on, match:tag floating-window
windowrule = size 875 600, match:tag floating-window


source = ~/.config/hypr/default/apps.conf
