# https://wiki.hyprland.org/Configuring/Configuring-Hyprland/

################
### MONITORS ###
################
source = ~/.config/hypr/default/monitors.conf

#############################
### ENVIRONMENT VARIABLES ###
#############################
source = ~/.config/hypr/default/envs.conf

#################
### AUTOSTART ###
#################
source = ~/.config/hypr/default/autostart.conf

#####################
### LOOK AND FEEL ###
#####################
source = ~/.config/hypr/default/looknfeel.conf

#############
### INPUT ###
#############
source = ~/.config/hypr/default/input.conf 

###################
### KEYBINDINGS ###
###################
source = ~/.config/hypr/default/bindings.conf

##############################
### WINDOWS AND WORKSPACES ###
##############################
source = ~/.config/hypr/default/windows.conf

# NVIDIA environment variables
env = NVD_BACKEND,direct
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
