#  _                      _            _    
# | |__  _   _ _ __  _ __| | ___   ___| | __
# | '_ \| | | | '_ \| '__| |/ _ \ / __| |/ /
# | | | | |_| | |_) | |  | | (_) | (__|   < 
# |_| |_|\__, | .__/|_|  |_|\___/ \___|_|\_\
#        |___/|_|                           
# 

# background {
#     monitor =
#     path = $HOME/.config/wallpapers/current-wallpaper.jpg # supports png, jpg, webp (no animations, though)
#     color = rgba(25, 20, 20, 1.0)
#
#     # all these options are taken from hyprland, see https://wiki.hyprland.org/Configuring/Variables/#blur for explanations
#     blur_passes = 2 # 0 disables blurring
#     blur_size = 4
#     noise = 0.0117
#     contrast = 0.8916
#     brightness = 0.8172
#     vibrancy = 0.1696
#     vibrancy_darkness = 0.0
# }

# ────────────────────────────────────────────────────────────
#  Hyprlock — Kanagawa theme
# ────────────────────────────────────────────────────────────

$color = rgba(31,31,40,1.0)  # #1f1f28 solid color

$inner_color = rgba(31,31,40,0.8)  # #1f1f28 with opacity
$outer_color = rgba(220,215,186,1.0)  # #dcd7ba

$font_color = rgba(220,215,186,1.0)

$placeholder_color = rgba(220,215,186,0.6)
$check_color = rgba(126, 156, 216, 1.0)

general {
    disable_loading_bar = true
    no_fade_in = false
}

background {
    monitor =
    color = $color
}

animations {
    enabled = false
}

input-field {
    monitor =
    size = 600, 100
    position = 0, 0
    halign = center
    valign = center

    inner_color = $inner_color
    outer_color = $outer_color
    outline_thickness = 4

    font_family = CaskaydiaMono Nerd Font
    font_size = 32
    font_color = $font_color

    placeholder_color = $placeholder_color
    placeholder_text =   Enter Password 󰈷 
    check_color = $check_color
    fail_text = Wrong

    rounding = 0
    shadow_passes = 0
    fade_on_empty = false
}
