unbind r
bind r source-file ~/.tmux.conf

# Enable 256-color and true-color (24-bit) support in tmux
set -g default-terminal "screen-256color" # Set terminal type for 256-color support
set -ga terminal-overrides ",*256col*:Tc" # Override to enable true-color for compatible terminals

set -g prefix M-s
set -g base-index 1
set -g mouse on

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

gray_light="#c0caf5"
gray_dark="#414868"
green="#9ece6a"
cyan="#2ac3de"
magenta="#bb9af7"
seafoam_green="#73daca"
pale_blue="#7dcfff"


set -g status-position top
set -g renumber-windows on
set -g status-left-length 100
set -g status-style "fg=${gray_light},bg=default"
set -g status-left "#[fg=${magenta},bold] #S #[fg=${gray_light},nobold] | "
set -g window-status-current-format "#[fg=${seafoam_green},bold] #[underscore]#I:#W#[nounderscore]"
set -g window-status-format " #I:#W"
set -g message-style "fg=${gray_light},bg=default"
set -g mode-style "fg=${gray_dark},bg=${pale_blue}"
set -g status-right "#{?window_bigger,[#{window_offset_x}#,#{window_offset_y}] ,}%H:%M %d-%b-%y"

### Display Popups
bind C-y display-popup -d "#{pane_current_path}" \
    -w 80% \
    -h 80% \
    -E "lazygit"
